apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailspin-web
  labels:
    app: tailspin-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailspin-web
  template:
    metadata:
      labels:
        app: tailspin-web
    spec:
      containers:
      - name: tailspin-web
        image: nginx:latest 
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "250m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
